# Prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix
# Mouse
set -g mouse on
# Copy mode: vi
setw -g mode-keys vi
# 256 colors / truecolor
set -g default-terminal "tmux-256color"
set -ga terminal-features ",xterm-256color:RGB"
# Clipboard
set -g set-clipboard on
# History
set -g history-limit 10000
# Faster escape
set -sg escape-time 10
# Start windows/panes at 1
set -g base-index 1
setw -g pane-base-index 1
# Don't rename windows automatically
set -g allow-rename off

# Status
set -g status-position bottom
set -g status-style "bg=#0D1117,fg=#00FF9C"

set -g status-left "#[fg=#00FF9C] #S "
set -g status-left-length 30

set -g status-right "#[fg=#55CFA5] %H:%M "

set -g window-status-format "#[fg=#55CFA5] #I:#W "
set -g window-status-current-format "#[fg=#00FF9C] #I:#W "
set -g window-status-current-style "bg=#1D2925"
