import = ["/home/gabox/.config/alacritty/colorscheme.toml"]

[cursor.style]
shape = "Block"

[font]
size = 14

[font.bold]
family = "IBM Plex Mono Text"
style = "Bold"

[font.italic]
family = "IBM Plex Mono Text"
style = "Italic"

[font.normal]
family = "IBM Plex Mono Text"
style = "Regular"

[window.padding]
x = 5
y = 5
