require('packer_init')

require('core/options')
require('core/keymaps')
require('core/colors')
require('core/autocmds')

require('plugins/nvim-tree')
require('plugins/fzf')
require('plugins/nvim-neogit')
require('plugins/gitsigns')
require('plugins/startpage')
require('plugins/status')
require('plugins/nvim-treesitter')
require('plugins/nvim-treesitter-context')
require('plugins/nvim-lspconfig')
